import SwiftUI

// AUTO-GENERATED Philippine vendor catalog (2026-06-10). ~700 consumer brands so vendor tiles
// resolve a real logo (via BrandLogoStore measure-and-pick) instead of a letter chip. Domains
// are best-effort; an unreachable one simply falls back to the brand color + SF Symbol below.
// Searched AFTER the hand-curated VendorBrand.table, so curated entries always win.
extension VendorBrand {
    static let phCatalog: [(needles: [String], hex: String, symbol: String, domain: String?)] = [
        (["2go express", "two go"], "#FF6B00", "shippingbox.fill", "2go.com.ph"),
        (["2jc construction", "jc construction supply", "jc construction"], "#1F497D", "building.2.fill", "jmconstruction.com.ph"),
        (["aamco", "aamcoph"], "#003DA5", "wrench.and.screwdriver.fill", "aamco.com"),
        (["aba live"], "#00A3E0", "film.fill", "abalive.ph"),
        (["abenson"], "#004B9E", "storefront.fill", "abenson.com.ph"),
        (["aboitizpower", "aboitiz"], "#00529B", "bolt.fill", "aboitizpower.com"),
        (["abscbn", "abs cbn credit"], "#1E90FF", "creditcard.fill", "abscbncredit.com.ph"),
        (["accredited dent", "accredited dental"], "#00695C", "cross.case.fill", "accrediteddental.com.ph"),
        (["ace hardware philippines", "acehardware"], "#D32F2F", "hammer.fill", "acehardrware.com.ph"),
        (["acer"], "#79B818", "desktopcomputer", "acer.com.ph"),
        (["adams", "adams stationery"], "#0066CC", "pencil.and.ruler.fill", "adamsstationery.com.ph"),
        (["adidas"], "#000000", "shoe.fill", "adidas.com.ph"),
        (["advanced diagnostics", "adx diagnostics"], "#0277BD", "stethoscope", "adxlabs.com.ph"),
        (["aeon", "aeon mall", "aeon supermarket"], "#003DA5", "storefront.fill", "aeon.ph"),
        (["affiliated tellers"], "#003DA5", "building.2.fill", "atm.com.ph"),
        (["airasia philippines", "airasia"], "#FF0000", "airplane", "airasia.com"),
        (["akyat", "akyatbox"], "#ff6b35", "shippingbox.fill", "akyat.com.ph"),
        (["aldo shoes", "aldo"], "#000000", "shoe.fill", "aldoshoes.com.ph"),
        (["alfa mart", "alfa"], "#FFB81C", "storefront.fill", "alfamart.com.ph"),
        (["alibaba 1688", "1688"], "#E02E04", "storefront.fill", "1688.com"),
        (["aliexpress", "aliexpress.com"], "#E02E04", "cart.fill", "aliexpress.com"),
        (["allan", "allan city"], "#ff6b35", "basket.fill", "allancity.com.ph"),
        (["allday", "all day"], "#FF6B35", "storefront.fill", "allday.com.ph"),
        (["allhome.com.ph", "all home", "allhome"], "#E74C3C", "house.fill", "allhome.com.ph"),
        (["aloha", "aloha pharmacy"], "#0066CC", "pills.fill", "alohapharmacy.ph"),
        (["alpha"], "#FFD100", "storefront.fill", "alphasupermarket.ph"),
        (["amber bistro", "amber restaurant"], "#FFBF00", "fork.knife", "amberrestaurant.com.ph"),
        (["andalan cable"], "#006699", "tv.fill", "andalancable.ph"),
        (["andoks", "andok's"], "#E84033", "takeoutbag.and.cup.and.straw.fill", "andoks.com.ph"),
        (["angel's burger"], "#E84033", "fork.knife", "angelsburger.com.ph"),
        (["angkas delivery"], "#FF6600", "car.fill", "angkas.com"),
        (["aristocrat restaurant"], "#8B4513", "fork.knife", "aristocrat.com.ph"),
        (["armynavy"], "#003DA5", "takeoutbag.and.cup.and.straw.fill", "armynavyusa.com"),
        (["ascof pharmacy", "ascof"], "#00897B", "pills.fill", "ascof.com.ph"),
        (["asgarcia", "a.s. garcia"], "#C41E3A", "wrench.and.screwdriver.fill", "asgarcia.com.ph"),
        (["ashley furniture", "ashley homestore"], "#333333", "sofa.fill", "store.ashleyfurniture.ph"),
        (["asus"], "#000000", "gamecontroller.fill", "asus.com.ph"),
        (["audi", "audiph"], "#C41E3A", "car.fill", "audi.com.ph"),
        (["auto", "auto2000", "autopro"], "#E11D2A", "wrench.and.screwdriver.fill", "auto2000.com.ph"),
        (["autoco", "autocoparts"], "#E11D2A", "wrench.and.screwdriver.fill", "autoco.com.ph"),
        (["autohubph", "autohub"], "#E11D2A", "wrench.and.screwdriver.fill", "autohub.com.ph"),
        (["autoplusph", "autoplus"], "#003DA5", "wrench.and.screwdriver.fill", "autoplus.com.ph"),
        (["avent", "philips avent"], "#0066CC", "figure.and.child.holdinghands", "avent.com.ph"),
        (["avidshop", "avid"], "#E11D2A", "wrench.and.screwdriver.fill", "avidshop.com.ph"),
        (["avon ph", "avon philippines"], "#8B0000", "gift.fill", "avon.com.ph"),
        (["awsi", "ayalawater", "ayala water"], "#1B4F9E", "drop.fill", "ayalawater.com.ph"),
        (["ayala mall", "ayala malls"], "#003B6B", "storefront.fill", "ayalamalls.com"),
        (["baby bear", "babybear"], "#8B4513", "figure.and.child.holdinghands", "babybear.com.ph"),
        (["baby company", "baby company philippines"], "#87CEEB", "figure.and.child.holdinghands", "babycompany.com.ph"),
        (["baleadas", "salvadorian"], "#DAA520", "fork.knife", "baleadas.ph"),
        (["balescoatings", "bales coatings", "bales"], "#1C3A70", "paintbrush.fill", "balescoatings.com"),
        (["banapple"], "#FFB81C", "takeoutbag.and.cup.and.straw.fill", "banapple.com.ph"),
        (["banco de oro"], "#003399", "building.2.fill", "bdo.com.ph"),
        (["bangood"], "#FF6B00", "desktopcomputer", "banggood.com"),
        (["bank of the philippines"], "#003DA5", "building.2.fill", "bpi.com.ph"),
        (["barrio fiesta"], "#E11D2A", "fork.knife", "barriofiesta.com.ph"),
        (["basa supermarket", "basa"], "#FF0000", "storefront.fill", "basa.com.ph"),
        (["basta pasta"], "#FF0000", "fork.knife", "bastapasta.com.ph"),
        (["bataanarmy", "bataan"], "#C41E3A", "fuelpump.fill", "bataanarmy.com.ph"),
        (["bayad", "bayad center"], "#00A8E8", "storefront.fill", "bayad.com.ph"),
        (["bayan", "bayan telecommunications"], "#1F5296", "antenna.radiowaves.left.and.right", "bayan.com.ph"),
        (["bayantel"], "#0066CC", "antenna.radiowaves.left.and.right", "bayantel.net"),
        (["bdo auto", "bdo finance"], "#003399", "car.fill", "bdofinance.com.ph"),
        (["beacon pharmacy", "beacon"], "#FF6B35", "pills.fill", "beaconpharmacy.com.ph"),
        (["beats"], "#1D1D1D", "headphones", "beats.com"),
        (["beauty bar"], "#FF1493", "sparkles", "thebeautybar.ph"),
        (["beauty mnl", "beautymnl"], "#FF1493", "sparkles", "beautymnl.com"),
        (["belo", "belo medical group"], "#D4AF37", "sparkles", "belo.com.ph"),
        (["belo aqua"], "#00B8E6", "drop.fill", "beloaqua.com"),
        (["belo essential", "belo plus"], "#D4AF37", "sparkles", "belo.com.ph"),
        (["bench", "bench philippines"], "#FF0000", "tshirt.fill", "benchtaiwan.com"),
        (["bench body"], "#000000", "tshirt.fill", "bench.com.ph"),
        (["bershka"], "#000000", "tshirt.fill", "bershka.com.ph"),
        (["best denki"], "#E20019", "storefront.fill", "bestdenki.com.ph"),
        (["beyond"], "#00A4EF", "storefront.fill", "beyond.com.ph"),
        (["birkenstock"], "#694D3C", "shoe.fill", "birkenstock.com"),
        (["bj mart"], "#FF0000", "storefront.fill", "bjmart.com.ph"),
        (["black insomnia"], "#000000", "cup.and.saucer.fill", "blackinsomnia.com"),
        (["blims fine furniture", "blims", "blimsfurniture"], "#2C5282", "sofa.fill", "blimsfurniture.com.ph"),
        (["bloomnation"], "#ff69b4", "gift.fill", "bloomnation.com"),
        (["blue boy", "blueboy resort", "blueboy"], "#0066CC", "building.2.fill", "blueboyresort.com"),
        (["bmwph"], "#003DA5", "car.fill", "bmw.com.ph"),
        (["bo's coffee"], "#6B4423", "cup.and.saucer.fill", "boscoffee.com"),
        (["bonanza steakhouse"], "#8B4513", "fork.knife", "bonanzasteakhouse.com.ph"),
        (["boracay", "boracay resorts"], "#0066CC", "building.2.fill", "boracay.com"),
        (["bosch", "boschph"], "#E20019", "wrench.and.screwdriver.fill", "bosch-home.com.ph"),
        (["bose"], "#000000", "headphones", "bose.com"),
        (["botika", "botika drugstore"], "#4CAF50", "pills.fill", "botika.ph"),
        (["br eyewear"], "#000000", "eyeglasses", "breyewear.com.ph"),
        (["brandyautos", "brandy"], "#E11D2A", "car.fill", "brandyautos.com.ph"),
        (["brew tap taproom"], "#D2691E", "cup.and.saucer.fill", "brewtaptaproom.com"),
        (["bridgestone", "tiresph", "bridgestoneph", "tires"], "#E11D2A", "car.fill", "bridgestonetyres.com.ph"),
        (["brown sugar boba"], "#8B4513", "cup.and.heat.waves.fill", "brownsugarph.com"),
        (["bubba gump", "bubbagump", "bubba gump shrimp"], "#FF6B35", "fork.knife", "bubbagump.com"),
        (["bulacan online", "bulacanonline"], "#0066CC", "storefront.fill", "bulacanonline.com"),
        (["bureau revenue"], "#003DA5", "banknote.fill", "bir.gov.ph"),
        (["burger steak"], "#8B4513", "fork.knife", "burgersteak.ph"),
        (["bydautos"], "#C41E3A", "car.fill", "byd.com.ph"),
        (["cablelink"], "#003399", "tv.fill", "cablelink.ph"),
        (["cachedseries", "chdci", "cebuheights"], "#E11D2A", "bolt.fill", "chdci.com.ph"),
        (["cafe cabalen"], "#C41E3A", "fork.knife", "cabalenph.com"),
        (["cafe tipas"], "#8B4513", "fork.knife", "cafetipas.com.ph"),
        (["cainiao logistics", "cainiao"], "#ff6b00", "shippingbox.fill", "cainiao.com"),
        (["calea"], "#3E2723", "cup.and.saucer.fill", "caleacoffee.com.ph"),
        (["calix home internet"], "#0066CC", "wifi", "calix.com"),
        (["caltexphil", "caltexph"], "#FFCC00", "fuelpump.fill", "caltex.com.ph"),
        (["calvin klein"], "#000000", "tshirt.fill", "calvinklein.com.ph"),
        (["canon"], "#E4002B", "camera.fill", "canon.com.ph"),
        (["cardio center", "cardiocenter"], "#C62828", "heart.fill", "cardiocenter.com.ph"),
        (["care.ph"], "#2E7D32", "stethoscope", "care.ph"),
        (["careline"], "#00A86B", "drop.fill", "careline.com.ph"),
        (["carousell", "carousell.ph"], "#FF6B35", "cart.fill", "carousell.com"),
        (["carpartsph", "carparts"], "#003DA5", "wrench.and.screwdriver.fill", "carparts.com.ph"),
        (["casa aranda"], "#8B0000", "fork.knife", "casaaranda.com.ph"),
        (["cathay pacific", "cathay"], "#006B3F", "airplane", "cathaypacific.com"),
        (["cdmx logistics", "cdmx"], "#0066cc", "shippingbox.fill", "cdmx.com.ph"),
        (["cdo supermarket"], "#C41E3A", "storefront.fill", "cdomeats.com"),
        (["cebuair", "cebu pacific"], "#0066CC", "airplane", "cebupacificair.com"),
        (["cebuhomebuilders", "cebu home builders", "cebu home and builders centre"], "#004B87", "building.2.fill", "cebuhomebuilders.com"),
        (["centerpoint"], "#FF6600", "storefront.fill", "centerpoint.com.ph"),
        (["century chemical", "century chemical corp", "centurychemical"], "#1C4587", "paintbrush.fill", "centurychemical.com.ph"),
        (["ceres", "ceres bus", "cbco"], "#0066CC", "bus.fill", "ceresbus.com"),
        (["cetaphil"], "#007FFF", "drop.fill", "cetaphil.com.ph"),
        (["changan", "changanautos"], "#C41E3A", "car.fill", "changan.com.ph"),
        (["charles and keith", "charles & keith"], "#000000", "handbag.fill", "charlesandkeith.com.ph"),
        (["charter chemical", "charter chemical and coating", "charter coating"], "#222B69", "paintbrush.fill", "daviespaints.com.ph"),
        (["chatime"], "#FF6B35", "cup.and.heat.waves.fill", "chatime.com.ph"),
        (["cherry mobile", "cherry"], "#DC143C", "iphone", "cherrymobile.com"),
        (["chevrolet", "chevyph"], "#003DA5", "car.fill", "chevrolet.com.ph"),
        (["chevron", "chevronph"], "#0080D0", "fuelpump.fill", "chevron.com"),
        (["chfc", "chickenjoy"], "#E11D2A", "takeoutbag.and.cup.and.straw.fill", "chickenjoy.ph"),
        (["chicco", "chicco philippines"], "#FF0000", "figure.and.child.holdinghands", "chicco.com.ph"),
        (["chims peri peri"], "#FF0000", "fork.knife", "chimsperi.com.ph"),
        (["china bank", "chinabank"], "#E31C23", "building.2.fill", "chinabank.com.ph"),
        (["chinese general", "chinese general hospital"], "#E11D2A", "building.2.fill", "cgh.com.ph"),
        (["choco mucho"], "#6B4423", "birthday.cake.fill", "chocomucho.com.ph"),
        (["choice", "choice supermarket"], "#00CC00", "storefront.fill", "choice.com.ph"),
        (["chrissports", "chris sports"], "#003366", "dumbbell.fill", "chrissports.com"),
        (["chutney mexican"], "#228B22", "fork.knife", "chutneymexico.com"),
        (["cignal", "cignal tv"], "#0033CC", "tv.fill", "cignal.tv"),
        (["cimb", "cimb bank"], "#C60C30", "building.2.fill", "cimb.com.ph"),
        (["circleck", "circle k"], "#D91E18", "storefront.fill", "circlek.com.ph"),
        (["cityland mall", "cityland", "cityland malls"], "#003DA5", "storefront.fill", "cityland.ph"),
        (["clean fuel", "cleanfuel"], "#00AA4F", "fuelpump.fill", "cleanfuel.com.ph"),
        (["club par", "club paradise"], "#006633", "building.2.fill", "clubparadisepalawan.com"),
        (["coach"], "#CE8237", "handbag.fill", "coach.com.ph"),
        (["coco ice cream", "coco", "cocoicecream"], "#8B4513", "birthday.cake.fill", "cocoicecream.com"),
        (["coffee bean tea leaf"], "#8B4513", "cup.and.saucer.fill", "coffeebean.com"),
        (["coffee project"], "#5C4033", "cup.and.saucer.fill", "coffeeproject.ph"),
        (["coffee valley"], "#6B4423", "cup.and.saucer.fill", "coffeevalley.com.ph"),
        (["coins.money"], "#F5A623", "creditcard.fill", "coins.money"),
        (["coins.ph", "coins"], "#F5A623", "creditcard.fill", "coins.ph"),
        (["coles", "coles supermarket"], "#003DA5", "storefront.fill", "coles.com.ph"),
        (["common room", "commonroom"], "#FF69B4", "paintbrush.fill", "commonroomph.com"),
        (["conti's bakery", "conti's"], "#8B4513", "birthday.cake.fill", "contis.com.ph"),
        (["continentalph", "continental"], "#003DA5", "car.fill", "continental.com.ph"),
        (["converge ict"], "#FFC901", "wifi", "convergeict.com"),
        (["converse"], "#E0001F", "shoe.fill", "converse.com.ph"),
        (["corsair"], "#FFFF00", "gamecontroller.fill", "corsair.com"),
        (["cosco supermarket", "cosco"], "#FF0000", "storefront.fill", "coscosupermarket.com.ph"),
        (["cotton on"], "#009DE0", "tshirt.fill", "cottonon.com.ph"),
        (["couponese"], "#FF3333", "gift.fill", "couponese.com"),
        (["crateandbarrel", "crate barrel", "crate and barrel"], "#8B6F47", "sofa.fill", "crateandbarrel.com.ph"),
        (["crocs"], "#00A3A3", "shoe.fill", "crocs.com.ph"),
        (["crown regency", "crown"], "#FFD700", "building.2.fill", "crownregency.com"),
        (["ctbox", "collectors toy box"], "#333333", "gamecontroller.fill", "ctboxmanila.com"),
        (["cure", "cure drugstore"], "#0288D1", "pills.fill", "curedrug.ph"),
        (["daewoo"], "#C60C30", "tv.fill", "daewooelectronics.com.ph"),
        (["daihatsuph", "daihatsu"], "#E11D2A", "car.fill", "daihatsu.com.ph"),
        (["danco", "danco bus", "dansco"], "#0066AA", "bus.fill", "dancobus.com"),
        (["datablitz", "data blitz", "dblitz"], "#000000", "gamecontroller.fill", "datablitz.com.ph"),
        (["daviespaints", "davies paints", "davies paint"], "#222B69", "paintbrush.fill", "daviespaints.com.ph"),
        (["daymart", "day mart"], "#FF9900", "storefront.fill", "daymart.com.ph"),
        (["decathlon", "decath"], "#0082C3", "dumbbell.fill", "decathlon.ph"),
        (["dell"], "#007DB8", "desktopcomputer", "dell.com"),
        (["delonghi"], "#C41E3A", "cup.and.heat.waves.fill", "delonghi.com"),
        (["dencio's", "denciols"], "#B8302F", "fork.knife", "dencioslasagna.com"),
        (["denso", "densoph"], "#003DA5", "wrench.and.screwdriver.fill", "denso.com.ph"),
        (["dental clinic ph", "dentalcare"], "#FFFFFF", "cross.case.fill", "dentalcare.com.ph"),
        (["deped", "department education", "depedoph"], "#003DA5", "book.fill", "deped.gov.ph"),
        (["dermaline"], "#E8E8E8", "droplet.fill", "dermaline.com.ph"),
        (["dermatologist clinic", "dermatologists"], "#FF69B4", "cross.case.fill", "dermatologist.com.ph"),
        (["destiny cable"], "#004B87", "tv.fill", "destinycable.com.ph"),
        (["dia supermarket"], "#FF0000", "storefront.fill", "dia.com.ph"),
        (["dialysis center", "dialysis"], "#0097A7", "stethoscope", "dialysis.com.ph"),
        (["digital walker"], "#0066CC", "iphone", "digitalwalker.com.ph"),
        (["discovery suites", "discovery"], "#006699", "building.2.fill", "discoverysuites.com"),
        (["dito cmc", "dito telecommunity"], "#EA6D5F", "antenna.radiowaves.left.and.right", "ditocmc.com"),
        (["divisoria online", "divisoria"], "#FF5733", "cart.fill", "divisoriaonline.com"),
        (["diy hardware", "diyhardware"], "#FFC72C", "hammer.fill", "diyhardware.ph"),
        (["dmci power", "dmci"], "#005EB8", "bolt.fill", "dmcipower.com.ph"),
        (["dost", "science tech"], "#0033A0", "book.fill", "dost.gov.ph"),
        (["dove philippines", "dove"], "#FFFFFF", "drop.fill", "dove.com.ph"),
        (["dragonpay"], "#E31C23", "creditcard.fill", "dragonpay.com"),
        (["dream cable"], "#1B5E9A", "tv.fill", "dreamcable.ph"),
        (["dulux paint", "dulux", "dulux philippines"], "#A4D0E8", "paintbrush.fill", "akzonobel.com"),
        (["dunlopph", "dunlop"], "#003DA5", "car.fill", "dunlop.com.ph"),
        (["dynaquest", "dqpc", "dynaquestpc"], "#0066CC", "desktopcomputer", "dynaquestpc.com"),
        (["dyson"], "#40BEE0", "wrench.and.screwdriver.fill", "dyson.com"),
        (["e-plus stationery", "eplusstationery"], "#0066CC", "pencil.and.ruler.fill", "eplusstationery.com.ph"),
        (["east west bank"], "#003DA5", "building.2.fill", "eastwestbanker.com"),
        (["easttelco", "east telco"], "#0066BB", "antenna.radiowaves.left.and.right", "easttelco.ph"),
        (["easypc", "easy pc"], "#FF6600", "desktopcomputer", "easypc.com.ph"),
        (["easytrip", "easy trip"], "#ffc300", "car.fill", "easytrip.com.ph"),
        (["eknight mall", "eknightmall"], "#FF6600", "storefront.fill", "eknightmall.com"),
        (["electrolux"], "#004687", "wrench.and.screwdriver.fill", "electrolux.com.ph"),
        (["elips"], "#FFD700", "drop.fill", "elips.com.ph"),
        (["emirates", "emirate airways"], "#CC0000", "airplane", "emirates.com"),
        (["ensogo.ph", "ensogo"], "#00A4EF", "gift.fill", "ensogo.com"),
        (["eskinol"], "#0066CC", "drop.fill", "eskinol.com.ph"),
        (["eton centris"], "#8B0000", "storefront.fill", "etoncentris.com.ph"),
        (["ever commonwealth", "ever gotesco", "ever malls"], "#004B87", "storefront.fill", "evermalls.com.ph"),
        (["evotech", "evotech mart"], "#1E90FF", "storefront.fill", "evotechmart.com.ph"),
        (["exactlyfast"], "#006EC7", "shippingbox.fill", "exactlyfast.com"),
        (["eye care center", "eyecare"], "#5E35B1", "eyeglasses", "eyecarecenter.com.ph"),
        (["falken", "godyear"], "#FFD700", "car.fill", "falken.com.ph"),
        (["famimart"], "#FF6B35", "storefront.fill", "familymart.com.ph"),
        (["fashion nova"], "#FF1493", "tshirt.fill", "fashionnova.com"),
        (["fb marketplace", "marketplace"], "#1877F2", "storefront.fill", "facebook.com"),
        (["federal hardware", "federal hardware center", "federal builders"], "#003D82", "wrench.and.screwdriver.fill", "federalnorthhardware.com"),
        (["fedex", "federal express"], "#4d148c", "shippingbox.fill", "fedex.com"),
        (["fg builders", "fgbuilders", "fg builders depot"], "#ED1C24", "building.2.fill", "fgbuildersdepot.com"),
        (["fiber one"], "#0066FF", "wifi", "fiberoneph.com"),
        (["fiberx", "fiber x"], "#1B5E20", "wifi", "fiberx.com.ph"),
        (["figaro coffee"], "#8B6F47", "cup.and.saucer.fill", "figarocoffee.ph"),
        (["figaro coffee"], "#8B5A3C", "cup.and.saucer.fill", "figarocoffee.ph"),
        (["filam", "fil-american hardware", "filam hardware"], "#CC0000", "wrench.and.screwdriver.fill", "filam.com.ph"),
        (["fire service", "bureaufireprotection"], "#E11D2A", "building.columns.fill", "bfp.gov.ph"),
        (["fisher price"], "#FFD700", "figure.and.child.holdinghands", "fisherprice.com.ph"),
        (["fitbit"], "#00BCD4", "heart.fill", "fitbit.com"),
        (["fivestar", "five star bus"], "#FFD700", "bus.fill", "fivestarbus.com"),
        (["flawless", "flawless cosmetics"], "#FFB6C1", "sparkles", "flawlesscosmetics.ph"),
        (["folded & hung", "foldedandhung", "folded and hung"], "#1F4788", "tshirt.fill", "foldedandhung.com"),
        (["foodlocker"], "#ff0000", "fork.knife", "foodlocker.com.ph"),
        (["ford", "fordph"], "#003DA5", "car.fill", "ford.com.ph"),
        (["forever 21", "forever21"], "#000000", "tshirt.fill", "forever21.com.ph"),
        (["fossil"], "#8B7355", "handbag.fill", "fossil.com"),
        (["freshmart", "fresh mart"], "#228B22", "storefront.fill", "freshmart.ph"),
        (["fried chicken special"], "#8B0000", "takeoutbag.and.cup.and.straw.fill", "fcsphinc.com"),
        (["fruitas"], "#FFA500", "drop.fill", "fruitas.com.ph"),
        (["fujifilm"], "#FF0000", "camera.fill", "fujifilm.com"),
        (["fullybooked"], "#2E5090", "book.fill", "fullybookedonline.com"),
        (["fullybooked"], "#8B0000", "book.fill", "fullybooked.com.ph"),
        (["furniture republic", "furniturerepublic"], "#4A4A4A", "sofa.fill", "furniture-republic.com.ph"),
        (["furniturescource philippines", "furniture source"], "#333333", "sofa.fill", "furnituresourcephils.com"),
        (["gaisano group", "gaisano mall", "gaisano", "gaisano mart"], "#FFD700", "storefront.fill", "gaisano.com.ph"),
        (["gaisano malls", "gmall", "gaisano grand malls"], "#E20F0F", "storefront.fill", "gaisanomalls.com"),
        (["gapkids", "gap kids"], "#003087", "tshirt.fill", "gapkids.com"),
        (["garmin"], "#003DA5", "heart.fill", "garmin.com"),
        (["gcash"], "#00A4EF", "wallet.bifold.fill", "gcash.com"),
        (["geekbuying"], "#FF6B6B", "desktopcomputer", "geekbuying.com"),
        (["geekloveph", "geek love"], "#222222", "gamecontroller.fill", "geekloveph.com"),
        (["geely", "geelymotors"], "#003DA5", "car.fill", "geely.com.ph"),
        (["gen trans", "genesis transport", "genesis"], "#006633", "bus.fill", "genesistransport.com"),
        (["glo pharmacy"], "#00ACC1", "pills.fill", "glopharmacy.com.ph"),
        (["globalsphere", "gsat fiber", "gsat"], "#0066CC", "wifi", "gsat.com.ph"),
        (["gloria jean's", "gloriajeans", "gloria jeans"], "#8B4513", "cup.and.saucer.fill", "gloriajeanscoffees.com"),
        (["gocar", "gojek"], "#00AA00", "car.fill", "gojek.com"),
        (["goldilocks"], "#FFD700", "birthday.cake.fill", "goldilocks.com.ph"),
        (["goldwing", "goldwings"], "#FFD700", "pencil.and.ruler.fill", "goldwings.com.ph"),
        (["gong cha", "gongcha"], "#8B6914", "cup.and.saucer.fill", "gongcha.com"),
        (["goodyearph", "goodyear"], "#003DA5", "car.fill", "goodyear.com.ph"),
        (["gopro"], "#FF6B35", "camera.fill", "gopro.com"),
        (["goro ramen"], "#FF0000", "fork.knife", "gororamen.com.ph"),
        (["grand supermarket", "grand"], "#00A8E8", "storefront.fill", "grandsupermarket.com.ph"),
        (["great", "greatwall"], "#E11D2A", "car.fill", "great.com.ph"),
        (["guess"], "#E60012", "handbag.fill", "guess.com.ph"),
        (["habihome", "habi home"], "#8B7355", "basket.fill", "habihomeshop.com"),
        (["habitat manila", "habitat"], "#6B4423", "sofa.fill", "habitatmanila.ph"),
        (["handyman hardware", "handyman superstore", "handyman do it best", "handyman"], "#FF9800", "wrench.and.screwdriver.fill", "handyman.com.ph"),
        (["hankook", "hankookph"], "#C41E3A", "car.fill", "hankookph.com"),
        (["happyskin", "happy skin"], "#FFB6D9", "sparkles", "happyskin.com.ph"),
        (["hardwarehub", "hardware hub philippines", "hardware hub"], "#FF6600", "wrench.and.screwdriver.fill", "hardwarehub.ph"),
        (["hchem", "h-chem industries", "h chem"], "#003D82", "paintbrush.fill", "hchemindustries.com.ph"),
        (["healthline", "healthline clinic"], "#1565C0", "stethoscope", "healthline.com.ph"),
        (["henann", "henann group"], "#003366", "building.2.fill", "henanntouristicdevelop.com"),
        (["hennes mauritz"], "#FF4C00", "tshirt.fill", "hm.com.ph"),
        (["henry hotel", "henry"], "#663300", "building.2.fill", "henryhotel.com.ph"),
        (["herco trading", "herco", "herco hardware"], "#003366", "building.2.fill", "herco.com.ph"),
        (["hewlett packard"], "#0096D6", "desktopcomputer", "hp.com"),
        (["hilton"], "#003E5C", "building.2.fill", "hilton.com"),
        (["home atelier", "homeu", "homeu ph"], "#000000", "sofa.fill", "homeu.ph"),
        (["home works", "homeworks", "the homecenter"], "#1C4587", "house.fill", "homeworks.com.ph"),
        (["homemaker", "homemaker furniture"], "#A0522D", "sofa.fill", "homemakerfurniture.com"),
        (["homematters", "home matters"], "#4A4A4A", "sofa.fill", "homematters.ph"),
        (["hondaph", "honda"], "#ED1C24", "car.fill", "honda.com.ph"),
        (["honestbee"], "#ff6b35", "cart.fill", "honestbee.com"),
        (["huawei"], "#FF0000", "iphone", "huawei.com.ph"),
        (["hubbyte", "toy store"], "#0066CC", "gamecontroller.fill", "hubbytetoystore.com"),
        (["human heart nature"], "#8B4513", "leaf.fill", "humanheartnatureskincare.com"),
        (["hyperbolic pharmacy", "hyperbolic"], "#5E35B1", "pills.fill", "hyperbolic.com.ph"),
        (["hypercable"], "#FF3333", "tv.fill", "hypercable.com.ph"),
        (["hypermart"], "#FF6B35", "storefront.fill", "hypermart.com.ph"),
        (["hyundai", "hyundaiph"], "#003DA5", "car.fill", "hyundai.com.ph"),
        (["iams pet care", "iams"], "#FF6600", "pawprint.fill", "iams.com.ph"),
        (["icc telecom"], "#0099FF", "antenna.radiowaves.left.and.right", "icc.com.ph"),
        (["iceblast"], "#0066CC", "cup.and.saucer.fill", "iceblastcafe.com"),
        (["iemop", "market operator", "independent"], "#1B4F9E", "antenna.radiowaves.left.and.right", "iemop.ph"),
        (["ikea ph", "ikea philippines"], "#0051BA", "sofa.fill", "ikea.com"),
        (["iloilowater", "iloilo water"], "#0066CC", "drop.fill", "iloilowater.com.ph"),
        (["infinix"], "#00D4FF", "iphone", "infinixmobility.com"),
        (["infinix philippines"], "#1A1A1A", "iphone", "infinix.com"),
        (["instapay"], "#FF6B35", "creditcard.fill", "instapay.com.ph"),
        (["international house of pancakes", "ihop"], "#003DA5", "birthday.cake.fill", "ihop.com"),
        (["interpartsph", "interparts"], "#003DA5", "wrench.and.screwdriver.fill", "interparts.com.ph"),
        (["intra-muros", "intramuros"], "#8B4513", "building.2.fill", "intramurosadmin.gov.ph"),
        (["isetan"], "#c60a3a", "storefront.fill", "isetan.com.ph"),
        (["island paints", "islandpaints", "island premium paints"], "#E74C3C", "paintbrush.fill", "islandpaints.com"),
        (["islands restaurant"], "#003DA5", "fork.knife", "islandsrestaurant.com.ph"),
        (["isuzu", "isuzuph"], "#003DA5", "car.fill", "isuzu.com.ph"),
        (["itel philippines", "itel"], "#F52E2E", "iphone", "itel-mobile.com"),
        (["itsmocha"], "#8B4513", "cup.and.saucer.fill", "itsmocha.com"),
        (["iwant tv", "i want", "iwantv"], "#FF6600", "tv.fill", "iwantv.com.ph"),
        (["j&t express"], "#FF3333", "shippingbox.fill", "jtexpress.ph"),
        (["jacline", "jac liner"], "#003366", "bus.fill", "jacliners.com"),
        (["jamba juice"], "#FF6B35", "drop.fill", "jambajuice.com"),
        (["jaya supermarket", "jaya"], "#003DA5", "storefront.fill", "jayasupermarket.com.ph"),
        (["jcbph"], "#FFD700", "car.fill", "jcbindia.com"),
        (["jco donuts"], "#E74C3C", "birthday.cake.fill", "jcodonuts.com"),
        (["jetsway"], "#E11D2A", "fuelpump.fill", "jetswayph.com"),
        (["jintels", "jintelservice"], "#FF7A00", "antenna.radiowaves.left.and.right", "jintels.com.ph"),
        (["jotun", "jotun philippines", "jotun paint"], "#002B5C", "paintbrush.fill", "jotun.com"),
        (["jt express"], "#ff0000", "shippingbox.fill", "jtexpress.ph"),
        (["juno logistics", "juno"], "#4c51bf", "shippingbox.fill", "juno.com.ph"),
        (["jysk"], "#FF6B00", "sofa.fill", "jysk.com.ph"),
        (["kenny rogers", "kenny rogers roasters"], "#E11D2A", "takeoutbag.and.cup.and.straw.fill", "kennyrogersroasters.com"),
        (["khmtools", "khm megatools", "megatools"], "#FFC72C", "hammer.fill", "khmtools.com.ph"),
        (["kiaph"], "#C41E3A", "car.fill", "kia.com.ph"),
        (["korean garden", "korean garden bbq"], "#FF0000", "fork.knife", "koreangarden.com.ph"),
        (["kultura", "kultura bookstore"], "#8B4513", "storefront.fill", "kultura.com.ph"),
        (["kumho", "kumhoph"], "#003DA5", "car.fill", "kumho.com.ph"),
        (["kung fu tea"], "#D32F2F", "cup.and.saucer.fill", "kungfutea.com"),
        (["lab testing philippines", "labtesting"], "#00897B", "stethoscope", "labtesting.ph"),
        (["lacoste"], "#008000", "tshirt.fill", "lacoste.com.ph"),
        (["laguna", "laguna sip", "lisp"], "#005EB8", "bolt.fill", "lispweb.com"),
        (["lalamove", "lala"], "#FF6B00", "car.fill", "lalamove.com"),
        (["lamborghiniph", "lamborghini"], "#FFD800", "car.fill", "lamborghini.com"),
        (["landbank", "land bank"], "#0066CC", "building.2.fill", "landbank.com"),
        (["landers superstore"], "#006bb6", "storefront.fill", "landers.com.ph"),
        (["landmarkstore", "landmark supermarket", "landmark", "the landmark"], "#E31E24", "storefront.fill", "landmarkdept.com.ph"),
        (["lasikcenter", "lasik philippines"], "#7B1FA2", "eyeglasses", "lasikcenter.com.ph"),
        (["lawson"], "#0066B2", "storefront.fill", "lawson.com.ph"),
        (["lbc express", "lbc logistics"], "#E31C23", "shippingbox.fill", "lbcexpress.com"),
        (["lechon manok express", "lechon manok"], "#C41E3A", "fork.knife", "lechonmanok.com.ph"),
        (["lenovo"], "#E4001B", "desktopcomputer", "lenovo.com"),
        (["lens crafters", "lenscrafters"], "#0066CC", "eyeglasses", "lenscrafters.com.ph"),
        (["lexus", "lexusph"], "#003DA5", "car.fill", "lexus.com.ph"),
        (["lg electronics"], "#CC0000", "tv.fill", "lg.com"),
        (["liberty", "liberty broadband"], "#FF6600", "wifi", "libertyphil.com"),
        (["lifeline hospital", "lifeline"], "#D32F2F", "heart.fill", "lifeline.com.ph"),
        (["lilshobbycenter", "lil's hobby center", "lils hobby"], "#FF6600", "gamecontroller.fill", "lilshobbycenter.com.ph"),
        (["lion parcel"], "#0066cc", "shippingbox.fill", "lionparcel.com"),
        (["liquefied"], "#EE3124", "fuelpump.fill", "petronoil.com.ph"),
        (["logitech"], "#175DDA", "gamecontroller.fill", "logitech.com"),
        (["loreal", "l'oreal"], "#000000", "sparkles", "loreal.com.ph"),
        (["lspeed", "l speed"], "#FF9900", "wifi", "lspeed.com.ph"),
        (["lucky", "lucky supermarket"], "#FFD700", "storefront.fill", "luckysupermarket.com.ph"),
        (["lucky store"], "#FF6B35", "storefront.fill", "luckystore.com.ph"),
        (["lucky supermarket"], "#FF0000", "storefront.fill", "luckysupermarket.com.ph"),
        (["lugang chicken"], "#E11D2A", "takeoutbag.and.cup.and.straw.fill", "lugangchickenrice.com"),
        (["lulu hypermarket", "lulu"], "#FF6B35", "storefront.fill", "lulu.com"),
        (["lush", "lush cosmetics"], "#DC143C", "leaf.fill", "lush.com"),
        (["mabuhay hardware", "mabuhay lumber", "mabuhay sun trading"], "#E31937", "wrench.and.screwdriver.fill", "mabuhay.com.ph"),
        (["macbook", "apple", "iphone", "ipad"], "#000000", "iphone", "apple.com"),
        (["magpie supermarket", "magpie store", "magpie"], "#FF6B35", "storefront.fill", "magpiestore.ph"),
        (["makati", "makati supermarket"], "#003DA5", "storefront.fill", "makatisuper.com.ph"),
        (["makati medical", "makatimed"], "#004E89", "building.2.fill", "makatimedical.org"),
        (["malls supermarket", "malls", "malls group"], "#003DA5", "storefront.fill", "mallsgroup.com.ph"),
        (["mango"], "#C72C48", "tshirt.fill", "mango.com.ph"),
        (["manilaprince", "manila prince"], "#D4AF37", "fork.knife", "manilaprince.com.ph"),
        (["manilawater"], "#0099CC", "drop.fill", "manilawater.com.ph"),
        (["manuel", "manuel stationery"], "#003D82", "pencil.and.ruler.fill", "officesupplies.com.ph"),
        (["manulife", "manulife philippines"], "#E81B23", "heart.fill", "manulife.com.ph"),
        (["maria's spanish cuisine"], "#FFC400", "fork.knife", "mariasspanish.com.ph"),
        (["marinlao", "marilao gas"], "#FF9500", "fuelpump.fill", "marilaogas.com.ph"),
        (["marriott", "marriot"], "#B81C13", "building.2.fill", "marriott.com"),
        (["mary grace"], "#C41E3A", "birthday.cake.fill", "marygrace.com.ph"),
        (["maserati", "maseratiph"], "#003DA5", "car.fill", "maserati.com"),
        (["mataas.com", "mataas"], "#FF6B35", "cart.fill", "mataas.com"),
        (["max value", "max supermarket"], "#FF0000", "storefront.fill", "max.com.ph"),
        (["max's restaurant"], "#003366", "fork.knife", "maxsrestaurant.com.ph"),
        (["maxi collector", "maxicollector"], "#333333", "gamecontroller.fill", "maxicollector.com"),
        (["maxxisph", "maxxis"], "#C41E3A", "car.fill", "maxxis.com.ph"),
        (["maya", "maya app"], "#00B4E6", "wallet.bifold.fill", "maya.com.ph"),
        (["maybank", "may bank"], "#FFFFFF", "building.2.fill", "maybank.com.ph"),
        (["maybelline", "maybelline ph"], "#000000", "sparkles", "maybelline.com"),
        (["maynards restaurant", "maynards"], "#8B0000", "fork.knife", "maynards.com.ph"),
        (["maynila", "maynilawater"], "#003399", "drop.fill", "maynilad.com.ph"),
        (["mazda", "mazdaph"], "#C41E3A", "car.fill", "mazda.com.ph"),
        (["mech", "mechanix"], "#E11D2A", "wrench.and.screwdriver.fill", "mechanix.com.ph"),
        (["medcare", "med care clinic"], "#00838F", "pills.fill", "medcare.com.ph"),
        (["medela"], "#FFB81C", "figure.and.child.holdinghands", "medela.com.ph"),
        (["medicard"], "#1565C0", "heart.fill", "medicard.com.ph"),
        (["mediserve", "mediserve pharmacy"], "#00BCD4", "pills.fill", "mediserve.com.ph"),
        (["mega hardware", "mega construction", "mega hardware qc"], "#FFD700", "building.2.fill", "magnificenthardware.com"),
        (["meralc", "meralko"], "#1F77B4", "bolt.fill", "meralco.com.ph"),
        (["mercedes", "mercedesbenz"], "#003DA5", "car.fill", "mercedes-benz.com.ph"),
        (["metro bank", "metrobank"], "#E72C30", "building.2.fill", "metrobank.com.ph"),
        (["metro rail"], "#1B4F9E", "bus.fill", "lrt.gov.ph"),
        (["metro shoes", "metro supermarket", "metro"], "#0066CC", "storefront.fill", "metrosupermarket.com.ph"),
        (["michelinph", "michelin"], "#003DA5", "car.fill", "michelin.com.ph"),
        (["microsoft"], "#0078D4", "desktopcomputer", "microsoft.com"),
        (["microtel", "micro"], "#0066CC", "building.2.fill", "microtelph.com"),
        (["midasph", "midas"], "#C41E3A", "wrench.and.screwdriver.fill", "midas.com.ph"),
        (["mightyblue hobby", "mightyblue"], "#0066CC", "gamecontroller.fill", "mightybluehobbyshop.com"),
        (["minisoph", "miniso"], "#FF6B35", "basket.fill", "minisoph.com"),
        (["ministry of pizza"], "#E11D2A", "takeoutbag.and.cup.and.straw.fill", "ministryofpizza.com"),
        (["minute maid", "minutemaid"], "#FF6B35", "drop.fill", "minutemaid.com"),
        (["mistah donut", "mister donut"], "#EE1C25", "birthday.cake.fill", "misterdonut.com.ph"),
        (["mitsuph", "mitsubishi"], "#C41E3A", "car.fill", "mitsubishi-motors.com.ph"),
        (["mochimochi"], "#FFB6C1", "birthday.cake.fill", "mochimochi.com.ph"),
        (["mommy mundo"], "#FF1493", "figure.and.child.holdinghands", "mommymundo.com.ph"),
        (["monark", "monarkgarage"], "#E11D2A", "wrench.and.screwdriver.fill", "monark.com.ph"),
        (["moonleaf"], "#696969", "cup.and.saucer.fill", "moonleaf.com.ph"),
        (["most"], "#FF69B4", "leaf.fill", "most.com.ph"),
        (["mothercare", "mother care philippines"], "#FF69B4", "figure.and.child.holdinghands", "mothercare.com.ph"),
        (["motorola"], "#E4000B", "iphone", "motorola.com"),
        (["motorzone", "motorzoneoph"], "#E11D2A", "wrench.and.screwdriver.fill", "motorzone.com.ph"),
        (["move fitness", "moveconcept"], "#00A3E0", "dumbbell.fill", "tobys.com"),
        (["mr speedy", "mrspeedy", "mr. speedy"], "#FF0000", "car.fill", "mrspeedy.com"),
        (["mr. bean"], "#8B4513", "cup.and.saucer.fill", "mrbeanpizza.com.ph"),
        (["mr.diy", "bricolage philippines", "mrdiy"], "#FF6600", "hammer.fill", "mrdiy.com"),
        (["mrspeed", "mr speed"], "#ff0000", "car.fill", "mrspeed.com.ph"),
        (["mwss", "water authority"], "#0099CC", "drop.fill", "mwss.gov.ph"),
        (["my republic", "myrepublic"], "#FF6600", "wifi", "myrepublic.com.ph"),
        (["myfitness", "my fitness meal"], "#00aa00", "fork.knife", "myfitnessmeal.com.ph"),
        (["myinternet"], "#0066CC", "wifi", "myinternet.com.ph"),
        (["mynt", "mynt streaming"], "#FF6B35", "film.fill", "mynt.ph"),
        (["nappydays", "nappy days"], "#FFD700", "figure.and.child.holdinghands", "nappydays.com.ph"),
        (["national book store", "nationalbookstore"], "#CC0000", "book.fill", "nationalbookstore.com"),
        (["national bookstore", "natl bookstore"], "#0066CC", "book.fill", "nationalbookstore.com.ph"),
        (["national bureau investigation"], "#001A4D", "building.columns.fill", "nbi.gov.ph"),
        (["national power", "napocor"], "#003DA5", "bolt.fill", "napocor.gov.ph"),
        (["nationalbreadcompany"], "#E11D2A", "drop.fill", "nbc.com.ph"),
        (["nicco", "nicco supermarket"], "#00A8E8", "storefront.fill", "nicco.com.ph"),
        (["nichido", "nichido makeup"], "#C41E3A", "sparkles", "nichido.com.ph"),
        (["nike"], "#111111", "shoe.fill", "nike.com.ph"),
        (["nikon"], "#FFD700", "camera.fill", "nikonusa.com"),
        (["ninjavan", "ninja van"], "#00A4EF", "shippingbox.fill", "ninjavan.co"),
        (["nintendo"], "#E60012", "gamecontroller.fill", "nintendo.com"),
        (["nippon coatings", "nippon", "nippon paint"], "#F02B28", "paintbrush.fill", "nipponpaint.com.ph"),
        (["nissanph", "nissan"], "#C41E3A", "car.fill", "nissan.com.ph"),
        (["nitori", "nitori philippines"], "#0066CC", "sofa.fill", "nitori.com.ph"),
        (["nivea philippines"], "#003DA5", "drop.fill", "nivea.com.ph"),
        (["nolisoli", "noli soli"], "#8b4789", "bag.fill", "nolisoli.ph"),
        (["nothing"], "#000000", "iphone", "nothing.tech"),
        (["now broadband"], "#FF6B00", "wifi", "nowbroadband.ph"),
        (["nrcp", "national research", "nstp"], "#003366", "building.columns.fill", "nrcp.dost.gov.ph"),
        (["office warehouse", "officewarehouse"], "#0066CC", "pencil.and.ruler.fill", "officewarehouse.com.ph"),
        (["office works", "officeworks"], "#0066CC", "pencil.and.ruler.fill", "officeworks.ph"),
        (["olay", "olay philippines"], "#8B4513", "drop.fill", "olay.com.ph"),
        (["oldmanila", "old manila", "old manila coffee"], "#8B4513", "cup.and.saucer.fill", "oldmanilacoffee.com.ph"),
        (["oldnavy", "old navy"], "#003087", "tshirt.fill", "oldnavy.com"),
        (["olx.ph"], "#002F6C", "cart.fill", "olx.com.ph"),
        (["olympic", "olympic village"], "#FFD100", "dumbbell.fill", "olympicvillageunited.com"),
        (["oneplus"], "#F50514", "iphone", "oneplus.com"),
        (["ong chang"], "#D32F2F", "storefront.fill", "ongchang.com.ph"),
        (["ongkeco", "ongkeco hobby"], "#FF6600", "gamecontroller.fill", "ongkeco.com"),
        (["ongpin", "ong pin market"], "#FF0000", "storefront.fill", "ongpinmarket.com.ph"),
        (["oomph.ph", "oomph"], "#FF1493", "bag.fill", "oomph.ph"),
        (["opisina.com", "opisina"], "#0066CC", "pencil.and.ruler.fill", "opisina.com.ph"),
        (["oppo"], "#52C41A", "iphone", "oppo.com"),
        (["oppo philippines"], "#00C92B", "iphone", "oppo.com"),
        (["optical center", "optical"], "#00BCD4", "eyeglasses", "opticalcenter.com.ph"),
        (["optical express"], "#FF0066", "eyeglasses", "opticalexpress.com.ph"),
        (["optimax vision", "optimax"], "#7B1FA2", "eyeglasses", "optimax.com.ph"),
        (["orthopedic", "orthopedic clinic"], "#F57F17", "cross.case.fill", "orthopedic.com.ph"),
        (["our home", "our home ph", "ourhome"], "#000000", "sofa.fill", "ourhome.ph"),
        (["outback steakhouse", "outback"], "#8B4513", "fork.knife", "outbacksteakhouse.com"),
        (["outrigger"], "#009900", "building.2.fill", "outrigger.com"),
        (["pacific paint boysen", "boysen"], "#1F497D", "paintbrush.fill", "boysen.com.ph"),
        (["pag-ibig", "pagibig", "hdmf"], "#FFD700", "house.fill", "pagibig.gov.ph"),
        (["pagasa", "pagasapnb", "police"], "#006BA6", "antenna.radiowaves.left.and.right", "pagasa.dost.gov.ph"),
        (["pagcorbingo", "pagcor", "pag-cor", "gaming"], "#003366", "building.columns.fill", "pagcor.ph"),
        (["paint supplier", "pintura.ph", "pintura"], "#E63946", "paintbrush.fill", "pintura.ph"),
        (["palawanspg", "palawan", "pspg"], "#1B4F9E", "bolt.fill", "palawanspg.com.ph"),
        (["palmolive philippines"], "#2E7D32", "sparkles", "palmolive.com.ph"),
        (["pan de la cruz"], "#8B4513", "birthday.cake.fill", "pandela-cruz.com.ph"),
        (["pan de manila"], "#C17A38", "birthday.cake.fill", "panddemanila.com"),
        (["panasonic"], "#004687", "tv.fill", "panasonic.com.ph"),
        (["pay maya", "paymaya"], "#00B4E6", "wallet.bifold.fill", "paymaya.com"),
        (["payless", "pay less"], "#FF6B00", "storefront.fill", "payless.com.ph"),
        (["payless shoesource"], "#005EB8", "shoe.fill", "payless.com"),
        (["paypal"], "#003087", "wallet.bifold.fill", "paypal.com"),
        (["pcexpress", "pc express"], "#003366", "desktopcomputer", "pcx.com.ph"),
        (["pedigree", "pedigree philippines"], "#E74C3C", "pawprint.fill", "pedigree.com.ph"),
        (["penshoppe"], "#2F5496", "tshirt.fill", "penshoppe.com.ph"),
        (["pensio"], "#1E73E8", "wallet.bifold.fill", "pensio.com"),
        (["pepper lunch"], "#8B0000", "fork.knife", "pepperlunch.com.ph"),
        (["pesop", "pesopoint"], "#455A64", "stethoscope", "pesopoint.com.ph"),
        (["pet opia", "petopia"], "#FF6B35", "pawprint.fill", "petopia.com.ph"),
        (["petronpumps"], "#003D7A", "fuelpump.fill", "petron.com.ph"),
        (["petsave", "pet save"], "#4A90E2", "pawprint.fill", "petsave.com.ph"),
        (["pg express"], "#FFD700", "storefront.fill", "puregoldprice.com"),
        (["phil health", "philhealth"], "#003DA5", "cross.case.fill", "philhealth.gov.ph"),
        (["phil-health"], "#0033A0", "cross.case.fill", "philhealth.gov.ph"),
        (["philcoffee"], "#6B4423", "cup.and.saucer.fill", "philcoffee.ph"),
        (["philcomsat"], "#003D82", "antenna.radiowaves.left.and.right", "philcomsat.com.ph"),
        (["philippine airlines", "phils airlines"], "#003399", "airplane", "philippineairlines.com"),
        (["philippine long distance"], "#E11D2A", "antenna.radiowaves.left.and.right", "pldt.com.ph"),
        (["philippine national bank"], "#003DA5", "building.2.fill", "pnb.com.ph"),
        (["philips"], "#002E63", "lightbulb.fill", "philips.com.ph"),
        (["philtrust", "phil trust"], "#003D82", "building.2.fill", "philtrust.com.ph"),
        (["philux home", "philux furniture", "philux"], "#8B4513", "sofa.fill", "philux.ph"),
        (["phl express"], "#ff6b35", "shippingbox.fill", "phlexpress.com.ph"),
        (["phoenixfuels"], "#C41E3A", "fuelpump.fill", "phoenixfuels.com.ph"),
        (["pickaroo"], "#ff9500", "bag.fill", "pickaroo.ph"),
        (["pigeon philippines", "pigeon"], "#FF6B9D", "figure.and.child.holdinghands", "pigeon.com.ph"),
        (["pirelli", "pirelliph"], "#C41E3A", "car.fill", "pirelli.com"),
        (["pixel", "google"], "#4285F4", "iphone", "google.com"),
        (["playstation"], "#003087", "gamecontroller.fill", "playstation.com"),
        (["pncc", "philippine national"], "#1B4F9E", "bus.fill", "pncc.com.ph"),
        (["polo ralph lauren"], "#C41E3A", "tshirt.fill", "poloralphlauren.com.ph"),
        (["polyclinics", "polyclinic philippines"], "#00695C", "building.2.fill", "polyclinics.com.ph"),
        (["ponds philippines", "ponds"], "#87CEEB", "drop.fill", "ponds.com.ph"),
        (["popeyes louisiana", "popeyes"], "#CE1126", "takeoutbag.and.cup.and.straw.fill", "popeyesph.com"),
        (["porsche", "porscheph"], "#003DA5", "car.fill", "porsche.com"),
        (["positive telecom"], "#00A651", "antenna.radiowaves.left.and.right", "positivetelecom.ph"),
        (["pottery barn ph", "potterybarn", "pottery barn"], "#8B4513", "sofa.fill", "ssilife.com.ph"),
        (["powerbooks"], "#003D82", "book.fill", "powerbooks.com.ph"),
        (["powerhouse philippines", "powerhouse tools", "powerhouse"], "#1A1A1A", "hammer.fill", "powerhouse.com.ph"),
        (["price", "price mart", "pricemart"], "#00A8E8", "storefront.fill", "pricemart.com.ph"),
        (["professional regulation"], "#003DA5", "building.columns.fill", "prc.gov.ph"),
        (["project workshop", "projectworkshop"], "#FF6B35", "paintbrush.fill", "projectworkshopph.com"),
        (["pull and bear", "pull&bear", "pullandbear"], "#FF6B35", "tshirt.fill", "pullandbear.com.ph"),
        (["puma"], "#000000", "shoe.fill", "puma.com.ph"),
        (["pure beauty"], "#FF69B4", "sparkles", "purebeauty.com.ph"),
        (["puregold club"], "#FFD700", "storefront.fill", "puregoldprice.com"),
        (["puregold express", "puregold price club", "pure gold"], "#FFD700", "storefront.fill", "puregoldprice.com"),
        (["purina", "purina petcare"], "#C41E3A", "pawprint.fill", "purina.com.ph"),
        (["purk's"], "#E11D2A", "takeoutbag.and.cup.and.straw.fill", "purks.com.ph"),
        (["qatar airways", "qatar"], "#6B1C30", "airplane", "qatarairways.com"),
        (["qqcable"], "#E60012", "tv.fill", "qqcable.com"),
        (["quest", "quest diagnostics"], "#1B4F9E", "stethoscope", "questdiagnostics.com.ph"),
        (["quest hotel"], "#1E90FF", "building.2.fill", "questhotels.com"),
        (["racks bbq"], "#8B4513", "fork.knife", "racksbbq.com.ph"),
        (["rain or shine", "asian coatings", "asian coatings philippines"], "#003DA5", "paintbrush.fill", "asiancoatings.com"),
        (["ramada"], "#003D5C", "building.2.fill", "ramada.com"),
        (["ramen yushoken"], "#FFD700", "fork.knife", "ramenyushoken.com.ph"),
        (["razer"], "#00FF00", "gamecontroller.fill", "razer.com"),
        (["razon's", "razons"], "#E11D2A", "takeoutbag.and.cup.and.straw.fill", "razons.com.ph"),
        (["rcbc", "rizal commercial banking"], "#1F5BA8", "building.2.fill", "rcbc.com.ph"),
        (["realme"], "#FFB81C", "iphone", "realme.com"),
        (["realme philippines"], "#FFC300", "iphone", "realme.com"),
        (["redribbon", "red-ribbon", "red ribbon", "red ribbon bakeshop"], "#E11D2A", "birthday.cake.fill", "redribbon.com.ph"),
        (["reecos"], "#C41E3A", "storefront.fill", "reecos.com.ph"),
        (["regatta"], "#C41E3A", "tshirt.fill", "regattacorp.com"),
        (["remate"], "#ff6b35", "cart.fill", "remate.com.ph"),
        (["remitly"], "#2CB1BC", "dollarsign.circle.fill", "remitly.com"),
        (["revlon ph"], "#FF0000", "sparkles", "revlon.com"),
        (["revolut"], "#262626", "creditcard.fill", "revolut.com"),
        (["riamoneytransfer"], "#E31C23", "dollarsign.circle.fill", "riafinancial.com"),
        (["rice baby"], "#DAA520", "fork.knife", "ricebaby.ph"),
        (["rich mama"], "#DAA520", "takeoutbag.and.cup.and.straw.fill", "richmama.ph"),
        (["rjs coffee", "rj's"], "#6B4423", "cup.and.saucer.fill", "rjscoffee.com"),
        (["robins express", "robinsons express"], "#004B87", "storefront.fill", "robinsons-retail.com.ph"),
        (["robinson", "robinsons department"], "#0066CC", "storefront.fill", "robinsonsretail.com.ph"),
        (["robinson appliances", "robinsons appliances"], "#C4182E", "tv.fill", "robinsonsappliances.com.ph"),
        (["robinson supermarket", "robinsons super"], "#C4182E", "cart.fill", "robinsonssupermarket.com.ph"),
        (["robinson's hotel"], "#003366", "building.2.fill", "robinsonshotelusc.com"),
        (["robinsons department store", "robdept", "robinsons dept"], "#C4182E", "bag.fill", "robinsonsdepartmentstore.com.ph"),
        (["robinsons place", "robinson malls"], "#C4182E", "storefront.fill", "robinsonsmalls.com"),
        (["robinsons retail", "robinsons malls", "robinson's"], "#0066CC", "storefront.fill", "robinsonsretail.com.ph"),
        (["rocket", "rocket internet"], "#FF3333", "wifi", "rocketbroadband.com.ph"),
        (["rosebud", "rosebud drugstore"], "#C2185B", "pills.fill", "rosebuddrug.com.ph"),
        (["rotonda", "rotondaauto"], "#C41E3A", "wrench.and.screwdriver.fill", "rotonda.com.ph"),
        (["royal canin"], "#8B4513", "pawprint.fill", "royalcanin.com.ph"),
        (["ruby salon"], "#DC143C", "scissors", "rubysalon.com.ph"),
        (["runnr"], "#00A3E0", "sportscourt.fill", "runnr.com.ph"),
        (["rural bank"], "#1E90FF", "building.2.fill", "ruralbankphil.com"),
        (["rustan supermarket", "rustan"], "#8B0000", "storefront.fill", "rustans.com"),
        (["rustan's", "rustons"], "#003B6B", "bag.fill", "rustans.com"),
        (["rustans supermarket", "rustans department store", "rustans"], "#8B0000", "storefront.fill", "rustans.com"),
        (["s and r"], "#FF6600", "storefront.fill", "snrmembers.com"),
        (["saizen", "daiso japan"], "#FF6B35", "basket.fill", "robinsonsretailholdings.com.ph"),
        (["saks fifth avenue"], "#000000", "handbag.fill", "saksfifthavenue.com"),
        (["sambo sambo"], "#DC143C", "fork.knife", "sambosambo.com.ph"),
        (["samsung", "samsung electronics"], "#1428A0", "tv.fill", "samsung.com"),
        (["save more"], "#FF6B35", "storefront.fill", "savemoreph.com"),
        (["sbarro", "sbarro pizza"], "#C41E3A", "takeoutbag.and.cup.and.straw.fill", "sbarrorestaurants.com"),
        (["school office", "adventurer"], "#0066CC", "pencil.and.ruler.fill", "adventurer.com.ph"),
        (["scribe writing", "scribe"], "#333333", "pencil.and.ruler.fill", "scribeph.com"),
        (["seafood island"], "#0066CC", "fork.knife", "seafoodisland.com.ph"),
        (["security bank", "securitybank"], "#1B3FA0", "building.2.fill", "securitybank.com.ph"),
        (["seda hotels", "seda"], "#003366", "building.2.fill", "sedahotels.com"),
        (["shangri", "shangri-la"], "#8B0000", "building.2.fill", "shangri-la.com"),
        (["shanti juice", "shanti"], "#FF6B35", "drop.fill", "shantijuice.com.ph"),
        (["sharp"], "#E20019", "tv.fill", "sharp.com.ph"),
        (["shein"], "#000000", "tshirt.fill", "shein.com"),
        (["shellph", "shellphil"], "#FFCC00", "fuelpump.fill", "shell.com.ph"),
        (["shinagawa", "shinagawa lasik"], "#E53935", "eyeglasses", "shinagawa.com.ph"),
        (["shiseido"], "#D4003A", "sparkles", "shiseido.com"),
        (["shoes company"], "#1E3A8A", "shoe.fill", "shoescompany.com.ph"),
        (["sinagore air", "singapore airlines"], "#003366", "airplane", "singaporeair.com"),
        (["skechers"], "#000000", "shoe.fill", "skechers.com.ph"),
        (["skincare.ph", "skin care ph"], "#E8D4C8", "leaf.fill", "skincare.ph"),
        (["skycable"], "#003DA5", "tv.fill", "skycable.com.ph"),
        (["sm cosmetics"], "#FF0000", "sparkles", "smcosmetics.com.ph"),
        (["sm electronics"], "#E31937", "storefront.fill", "smelectronics.com.ph"),
        (["sm fashion"], "#FF0000", "storefront.fill", "smfashion.com.ph"),
        (["sm malls", "smsupermarket", "sm grocery", "sm supermarket"], "#E31E24", "storefront.fill", "smsupermalls.com"),
        (["sm shopping", "sm supermalls", "smsupermalls"], "#F4B141", "storefront.fill", "smsupermalls.com"),
        (["sm stationery", "smstationery"], "#003D82", "pencil.and.ruler.fill", "smstationery.com.ph"),
        (["sm store", "sm department store", "the sm store"], "#F4B141", "bag.fill", "smstore.com"),
        (["smartkiosk", "smart kiosk"], "#00A3E0", "storefront.fill", "smartkiosk.com.ph"),
        (["smhome", "sm home"], "#F4B141", "house.fill", "smhome.ph"),
        (["smile studio", "smilestudio"], "#FFB300", "cross.case.fill", "smilestudio.com.ph"),
        (["smmart", "sm mart"], "#E41C3D", "storefront.fill", "smmall.com"),
        (["smsupermarkets"], "#C41E3A", "storefront.fill", "smsupermalls.com"),
        (["social security system", "sss.gov", "socialsecurity"], "#003DA5", "building.columns.fill", "sss.gov.ph"),
        (["soft", "sofitel"], "#8B7355", "cup.and.saucer.fill", "sofitelph.com"),
        (["solaneph", "solane"], "#E74C3C", "fuelpump.fill", "solane.com.ph"),
        (["sony", "sony philippines"], "#000000", "headphones", "sony.com.ph"),
        (["southstar drug"], "#E11D2A", "pills.fill", "southstardrug.com.ph"),
        (["sparko", "sparko coatings", "sparko surface coatings"], "#1B1B1B", "paintbrush.fill", "sparkocoatings.com"),
        (["sparksauto", "sparks"], "#E11D2A", "wrench.and.screwdriver.fill", "sparksauto.com.ph"),
        (["sportscentral", "sports central"], "#FF0000", "dumbbell.fill", "sportscentral.ph"),
        (["starry"], "#002F6C", "wifi", "starry.com"),
        (["stlukesmedical", "st luke's", "stlukes"], "#0066CC", "building.2.fill", "stlukesmedical.com"),
        (["stripe"], "#625BEE", "creditcard.fill", "stripe.com"),
        (["suavinex"], "#4169E1", "figure.and.child.holdinghands", "suavinex.com.ph"),
        (["subaru", "subaruph"], "#003DA5", "car.fill", "subaru.com.ph"),
        (["sulit spa"], "#FF69B4", "sparkles", "sulitspa.com.ph"),
        (["sun cellular"], "#FFB800", "antenna.radiowaves.left.and.right", "suncellular.com.ph"),
        (["sun rays", "sunrays", "sunrays bus"], "#FFA500", "bus.fill", "sunraysbus.com"),
        (["sun travel", "sunshine travel", "sunshine"], "#FFD700", "ticket.fill", "sunshinetravel.com.ph"),
        (["super globe paint", "superglobe", "super globe"], "#FF9933", "paintbrush.fill", "superglobe.com.ph"),
        (["supervalue", "super value"], "#003DA5", "storefront.fill", "supervalueph.com"),
        (["suzukiph", "suzuki"], "#003DA5", "car.fill", "suzuki.com.ph"),
        (["sxl express"], "#0066ff", "shippingbox.fill", "sxl.com.ph"),
        (["sycwin coating", "sycwin coating and wires", "sycwin"], "#003D82", "paintbrush.fill", "sycwin.com.ph"),
        (["taobao"], "#E02E04", "cart.fill", "taobao.com"),
        (["taters fries"], "#FFB81C", "takeoutbag.and.cup.and.straw.fill", "tatersfries.com"),
        (["tecno"], "#01A699", "iphone", "tecno.ph"),
        (["tecno philippines"], "#FF0000", "iphone", "tecno-mobile.com"),
        (["teriyaki boy"], "#FFD700", "fork.knife", "teriyakiboy.com.ph"),
        (["tforce logistics", "tforce"], "#ff6b35", "car.fill", "tforceexpress.com.ph"),
        (["thai airways"], "#003399", "airplane", "thaiairways.com"),
        (["the daily grind"], "#6B4423", "cup.and.saucer.fill", "thedailygrindph.com"),
        (["tiger sugar"], "#FF9800", "cup.and.heat.waves.fill", "tigersugar.com"),
        (["times paint", "timespaints", "times paint corp"], "#E74C3C", "paintbrush.fill", "timespaints.com.ph"),
        (["ting ting dimsum"], "#FFD700", "fork.knife", "tingtingdimsum.com.ph"),
        (["tobys", "toby's sports"], "#FF6600", "dumbbell.fill", "tobys.com"),
        (["tokyo tokyo", "tokyotokyo"], "#E11D2A", "fork.knife", "tokyotokyoph.com"),
        (["tolls", "dotr", "dotc", "ntmc"], "#1B4F9E", "car.fill", "dotc.gov.ph"),
        (["tommy hilfiger"], "#003087", "tshirt.fill", "tommy.com.ph"),
        (["tonik"], "#1E73E8", "iphone", "tonik.com"),
        (["top most", "top-most hardware", "topmost"], "#FF6600", "building.2.fill", "topmosthardware.ph"),
        (["topshop"], "#000000", "tshirt.fill", "topshop.com"),
        (["toshiba"], "#A00000", "tv.fill", "toshiba.com.ph"),
        (["totalenergies"], "#003DA5", "fuelpump.fill", "totalenergies.com.ph"),
        (["total access"], "#0066CC", "storefront.fill", "totalaccess.com.ph"),
        (["totaltools", "total tools philippines", "total tools"], "#FFC72C", "hammer.fill", "khmtools.com.ph"),
        (["toykingdom", "toy kingdom"], "#FF6B35", "gamecontroller.fill", "toykingdom.com.ph"),
        (["toyoph", "toyo"], "#003DA5", "car.fill", "toyotires.com.ph"),
        (["toyota", "toyotaph"], "#EB0A1E", "car.fill", "toyota.com.ph"),
        (["toysrus", "toys r us"], "#FFC72C", "gamecontroller.fill", "toysrus.com.ph"),
        (["transferwise", "wise"], "#00B9FF", "dollarsign.circle.fill", "wise.com"),
        (["transportationanddistribution", "transco"], "#003DA5", "bolt.fill", "transco.org.ph"),
        (["transportify", "transport"], "#007AFF", "car.fill", "transportify.com.ph"),
        (["tropical hut"], "#228B22", "fork.knife", "tropicalhut.com.ph"),
        (["true value hardware", "truevalue", "true value"], "#E31E24", "hammer.fill", "truevalue.com.ph"),
        (["twin palms"], "#006633", "building.2.fill", "twinpalms.com"),
        (["ugly duckling"], "#3D3D3D", "fork.knife", "uglyduckling.com.ph"),
        (["uncles johns", "uncle johns"], "#E84033", "takeoutbag.and.cup.and.straw.fill", "unclejonspizza.com"),
        (["uni asia", "uni-asia construction", "uni-asia hardware"], "#003D82", "building.2.fill", "uni-asia.com.ph"),
        (["uni wash", "uniwash"], "#0066CC", "storefront.fill", "uniwash.ph"),
        (["unilab pharmacy", "unilab"], "#D32F2F", "pills.fill", "unilab.com.ph"),
        (["unimart"], "#ff0000", "basket.fill", "unimart.com.ph"),
        (["unioil"], "#003DA5", "fuelpump.fill", "unioil.com.ph"),
        (["union bank", "unionbank"], "#E31C23", "building.2.fill", "unionbankph.com"),
        (["uniondigital", "union digital"], "#E31C23", "wallet.bifold.fill", "uniondigitalbank.com"),
        (["united paints", "united paint", "united paints inc"], "#C41E3A", "paintbrush.fill", "unitedpaints.tech"),
        (["unitop"], "#0066cc", "storefront.fill", "unitopsupermarket.com"),
        (["universal paint", "uniguard", "unipaints"], "#003D82", "paintbrush.fill", "universalpaint.com.ph"),
        (["uratex", "uratex beds", "uratex mattress"], "#003B6B", "sofa.fill", "uratex.com.ph"),
        (["urbanathletics", "urban athletics"], "#000000", "tshirt.fill", "urbanathletics.com.ph"),
        (["urbanconcepts", "urban concepts"], "#2C3E50", "sofa.fill", "urbanconcepts.ph"),
        (["uso store"], "#FF6B00", "storefront.fill", "uso.com.ph"),
        (["uyayi bakery", "uyayi"], "#FF69B4", "birthday.cake.fill", "uyayi.com.ph"),
        (["v-mall", "vmall", "v mall"], "#FFD700", "storefront.fill", "vmall.com.ph"),
        (["vans"], "#000000", "shoe.fill", "vans.com"),
        (["vet's best", "vetsbest"], "#006633", "cross.case.fill", "vetsbest.com.ph"),
        (["viber.com", "viber"], "#665CAC", "cart.fill", "viber.com"),
        (["victory", "victory liner"], "#CC0000", "bus.fill", "victoryliner.com"),
        (["vikings buffet", "vikings"], "#C41E3A", "takeoutbag.and.cup.and.straw.fill", "vikings.com.ph"),
        (["village vanguard", "villagevanguard"], "#FF1493", "storefront.fill", "village-vanguard.com.ph"),
        (["vincis", "vinci's bakery"], "#D2691E", "birthday.cake.fill", "vincis.com.ph"),
        (["vios cafe"], "#8B6F47", "cup.and.saucer.fill", "vioscafe.com.ph"),
        (["vipon"], "#FF6B00", "gift.fill", "vipon.com"),
        (["visayan electric", "veco"], "#003DA5", "bolt.fill", "veco.com.ph"),
        (["vitamin world", "vitaminworld"], "#009688", "pills.fill", "vitaminworld.com.ph"),
        (["vivamax"], "#FF0000", "film.fill", "vivamax.net"),
        (["vivo"], "#1989FA", "iphone", "vivo.com.ph"),
        (["vivo philippines"], "#2D5BBA", "iphone", "vivo.com"),
        (["vnh retail", "vnhr"], "#1A7F3B", "storefront.fill", "vnhrgroup.com"),
        (["volte coffee"], "#1a1a1a", "cup.and.saucer.fill", "voltecoffee.com"),
        (["vroom"], "#FF5500", "car.fill", "vroomtravel.com"),
        (["vtechparts", "vtech"], "#003DA5", "wrench.and.screwdriver.fill", "vtech.com.ph"),
        (["vwph", "volkswagen"], "#003DA5", "car.fill", "volkswagen.com.ph"),
        (["wacoal", "wacoal cafe"], "#8B4513", "cup.and.saucer.fill", "wacaclcoffee.com.ph"),
        (["walter mart", "walter mart malls"], "#0066CC", "storefront.fill", "waltermart.com.ph"),
        (["welcare", "welcare pharmacy"], "#1976D2", "pills.fill", "welcare.com.ph"),
        (["west elm", "westelm"], "#556B2F", "sofa.fill", "ssilife.com.ph"),
        (["western union"], "#FFCC00", "dollarsign.circle.fill", "westernunion.com"),
        (["whirlpool"], "#003A70", "wrench.and.screwdriver.fill", "whirlpool.com.ph"),
        (["whiskas", "whiskas cat food"], "#0099CC", "pawprint.fill", "whiskas.com.ph"),
        (["whole foods market", "whole foods"], "#006B3F", "leaf.fill", "wholefoodsmarket.com"),
        (["wilcon depot", "wilcon", "wilcon.com.ph"], "#00A3E0", "wrench.and.screwdriver.fill", "wilcon.com.ph"),
        (["wish"], "#C41E3A", "gift.fill", "wish.com"),
        (["wowmart"], "#ff6b35", "basket.fill", "wowmart.com.ph"),
        (["wta travel", "world travel tours"], "#003366", "ticket.fill", "wtaphl.com"),
        (["x store"], "#000000", "storefront.fill", "xstore.com.ph"),
        (["xbox"], "#107C10", "gamecontroller.fill", "xbox.com"),
        (["xiaomi"], "#FF6900", "iphone", "xiaomi.com.ph"),
        (["xtendpay", "xtend pay"], "#1E73E8", "wallet.bifold.fill", "xtendpay.com"),
        (["yaki mix", "yakimix"], "#FF4500", "fork.knife", "yakimix.com.ph"),
        (["yellowcab"], "#FDD835", "fork.knife", "yellowcabpizza.com.ph"),
        (["ynap", "yoox", "yoox net-a-porter"], "#000000", "bag.fill", "ynap.com"),
        (["yokohamph", "yokohama"], "#C41E3A", "car.fill", "yokohama.com.ph"),
        (["yong salon", "yong"], "#DAA520", "scissors", "yongsalon.com.ph"),
        (["yoshinoya"], "#E11D2A", "fork.knife", "yoshinoya.com.ph"),
        (["zaful"], "#FF6B9D", "tshirt.fill", "zaful.com"),
        (["zara"], "#1A1A1A", "tshirt.fill", "zara.com.ph"),
        (["zus coffee"], "#1a1a1a", "cup.and.saucer.fill", "zuscoffee.com"),
    ]
}
