import "server-only";
import type {
  Spend,
  SpendItem,
  SpendVendorLink,
  Vendor,
} from "@/lib/supabase/types";

// Price Drift Watch (#30) — surfaces creeping price increases on the same
// item at the same vendor over time. Pure-math layer; the AI commentary is
// generated by the Calm Weather brain on a per-need basis (we don't run
// dedicated Gemini calls here — pure data drives the chart, the AI weaves it
// into the larger story when relevant).
//
// Normalization is deliberately loose: lower + alphanum-collapse so "5kg rice",
// "5 kg rice", and "5kg Rice" all bucket together. The user can override via
// item edit when the AI gets it wrong.

const DAY_MS = 86_400_000;

export interface PriceDriftPoint {
  observedAt: string;
  unitPriceBase: number;
  paidBase: number;
  spendId: string;
}

export interface PriceDriftRead {
  itemNameNorm: string;
  vendorId: string | null;
  points: PriceDriftPoint[];
  // Drift summary
  firstSeenAt: string;
  lastSeenAt: string;
  firstPriceBase: number;
  lastPriceBase: number;
  // Percent change end-to-end. Positive = price rose.
  pctChange: number;
  // Linear slope (₱/day) — surfaces gradual creeps.
  slopePerDay: number;
  // "rising" | "steady" | "falling". Threshold: ±8% AND ≥ 60 days of
  // history OR ±15% with any history. Otherwise "steady".
  trend: "rising" | "steady" | "falling";
}

export function normalizeItemName(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/\p{Diacritic}+/gu, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

// Compile drift reads from spend_items rows tied to vendor-linked spends.
// Vendor-less items (spends without a linked vendor) still produce a drift
// read by item alone — useful for grocery items the user buys at varying
// stores. The unit price is computed naively as item.amount / 1; if the user
// logs a quantity in the item name ("5kg rice"), the bucket already groups
// like-with-like.
export function priceDriftReads(
  items: SpendItem[],
  spends: Spend[],
  links: SpendVendorLink[],
): PriceDriftRead[] {
  const spendById = new Map(spends.map((s) => [s.id, s] as const));
  const vendorBySpend = new Map<string, string>();
  for (const l of links) vendorBySpend.set(l.spend_id, l.vendor_id);

  // Bucket: itemNameNorm + vendorId → list of points.
  const buckets = new Map<string, { itemName: string; vendorId: string | null; pts: PriceDriftPoint[] }>();
  for (const it of items) {
    if (it.amount == null || it.amount <= 0) continue;
    const sp = spendById.get(it.spend_id);
    if (!sp) continue;
    const norm = normalizeItemName(it.name);
    if (!norm) continue;
    const vendorId = vendorBySpend.get(it.spend_id) ?? null;
    const key = `${vendorId ?? "_"}::${norm}`;
    const bucket = buckets.get(key) ?? { itemName: norm, vendorId, pts: [] };
    bucket.pts.push({
      observedAt: sp.spent_at,
      unitPriceBase: Number(it.amount),
      paidBase: Number(it.amount),
      spendId: sp.id,
    });
    buckets.set(key, bucket);
  }

  const reads: PriceDriftRead[] = [];
  for (const { itemName, vendorId, pts } of buckets.values()) {
    if (pts.length < 2) continue;
    pts.sort((a, b) => a.observedAt.localeCompare(b.observedAt));
    const first = pts[0];
    const last = pts[pts.length - 1];
    const firstDate = new Date(first.observedAt);
    const lastDate = new Date(last.observedAt);
    const days = Math.max(1, (lastDate.getTime() - firstDate.getTime()) / DAY_MS);
    const pctChange = first.unitPriceBase > 0 ? ((last.unitPriceBase - first.unitPriceBase) / first.unitPriceBase) * 100 : 0;
    const slopePerDay = (last.unitPriceBase - first.unitPriceBase) / days;
    let trend: PriceDriftRead["trend"] = "steady";
    if ((Math.abs(pctChange) >= 8 && days >= 60) || Math.abs(pctChange) >= 15) {
      trend = pctChange > 0 ? "rising" : "falling";
    }
    reads.push({
      itemNameNorm: itemName,
      vendorId,
      points: pts,
      firstSeenAt: first.observedAt,
      lastSeenAt: last.observedAt,
      firstPriceBase: first.unitPriceBase,
      lastPriceBase: last.unitPriceBase,
      pctChange,
      slopePerDay,
      trend,
    });
  }
  // Sort: rising first (biggest pct rise), then falling, then steady.
  reads.sort((a, b) => {
    if (a.trend === b.trend) return b.pctChange - a.pctChange;
    if (a.trend === "rising") return -1;
    if (b.trend === "rising") return 1;
    if (a.trend === "falling") return -1;
    return 1;
  });
  return reads;
}

export function vendorForDriftRead(read: PriceDriftRead, vendors: Vendor[]): Vendor | null {
  if (!read.vendorId) return null;
  return vendors.find((v) => v.id === read.vendorId) ?? null;
}
