import "server-only";
import { Type } from "@google/genai";
import { gemini, hasGemini } from "./gemini";
import { HEAVY_MODEL } from "./models";
import type {
  Spend,
  SpendVendorLink,
  Vendor,
} from "@/lib/supabase/types";

// Per-Vendor Heartbeat (#28) — for each known vendor, compute the cadence
// of visits + spend and detect whether the recent rhythm has shifted.
//
// "Fourth Jollibee this month. Usually one." That kind of line.
//
// Math is pure; Gemini writes the one-line read when the deterministic check
// surfaces a shift worth narrating. No AI call when nothing has shifted —
// the surface is silent by default.

const DAY_MS = 86_400_000;
const RECENT_WINDOW_DAYS = 30;
const BASELINE_WINDOW_DAYS = 180;

export interface VendorHeartbeat {
  vendor: Vendor;
  // Visit + spend rollups in the recent window vs the baseline window.
  recentVisits: number;
  recentSpendBase: number;
  baselineVisits: number;          // typical N over RECENT_WINDOW_DAYS, derived from BASELINE_WINDOW_DAYS
  baselineSpendBase: number;       // typical PHP over RECENT_WINDOW_DAYS, derived from BASELINE_WINDOW_DAYS
  // Shift in visits / spend relative to baseline (ratio). > 1 = above typical.
  visitsRatio: number;
  spendRatio: number;
  // Shift bucket — drives surfacing logic.
  shift: "below" | "typical" | "above" | "spike";
}

function spendsForVendor(spendIds: Set<string>, spends: Spend[]): Spend[] {
  return spends.filter((s) => spendIds.has(s.id));
}

function inLastDays(spend: Spend, now: Date, days: number): boolean {
  const t = new Date(spend.spent_at).getTime();
  return t >= now.getTime() - days * DAY_MS && t <= now.getTime();
}

export function vendorHeartbeat(
  vendor: Vendor,
  links: SpendVendorLink[],
  spends: Spend[],
  now: Date = new Date(),
): VendorHeartbeat {
  const ids = new Set(links.filter((l) => l.vendor_id === vendor.id).map((l) => l.spend_id));
  const mine = spendsForVendor(ids, spends);
  const recent = mine.filter((s) => inLastDays(s, now, RECENT_WINDOW_DAYS));
  const baselineRange = mine.filter((s) => inLastDays(s, now, BASELINE_WINDOW_DAYS) && !inLastDays(s, now, RECENT_WINDOW_DAYS));
  const recentVisits = recent.length;
  const recentSpendBase = recent.reduce((s, r) => s + Number(r.amount_base ?? 0), 0);
  // Pro-rate baseline back to RECENT_WINDOW_DAYS for comparable units.
  const baselineDays = Math.max(1, BASELINE_WINDOW_DAYS - RECENT_WINDOW_DAYS);
  const baselineVisits = (baselineRange.length / baselineDays) * RECENT_WINDOW_DAYS;
  const baselineSpendBase = (baselineRange.reduce((s, r) => s + Number(r.amount_base ?? 0), 0) / baselineDays) * RECENT_WINDOW_DAYS;
  const visitsRatio = baselineVisits > 0.25 ? recentVisits / baselineVisits : recentVisits > 0 ? 99 : 0;
  const spendRatio = baselineSpendBase > 100 ? recentSpendBase / baselineSpendBase : recentSpendBase > 0 ? 99 : 0;
  let shift: VendorHeartbeat["shift"] = "typical";
  if (visitsRatio === 99 || spendRatio === 99) shift = "spike";
  else if (visitsRatio >= 1.6 || spendRatio >= 1.6) shift = "above";
  else if (visitsRatio < 0.5 && recentVisits === 0) shift = "below";
  return {
    vendor,
    recentVisits,
    recentSpendBase,
    baselineVisits,
    baselineSpendBase,
    visitsRatio,
    spendRatio,
    shift,
  };
}

export interface VendorHeartbeatRead {
  heartbeats: VendorHeartbeat[];
  // The one-line narrative per worth-surfacing vendor. Generated by Gemini
  // when available; otherwise a deterministic mirror sentence.
  lines: Array<{ vendorId: string; line: string }>;
}

const RESPONSE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    lines: {
      type: Type.ARRAY,
      maxItems: 6,
      items: {
        type: Type.OBJECT,
        properties: {
          vendorId: { type: Type.STRING },
          line: { type: Type.STRING },
        },
        required: ["vendorId", "line"],
        propertyOrdering: ["vendorId", "line"],
      },
    },
  },
  required: ["lines"],
};

const SYSTEM_PROMPT = `You write one-line vendor cadence observations for a SOLO freelancer in San Pablo, Philippines. Base currency PHP.

For each vendor in the snapshot whose visit rhythm has shifted, write ONE line. Mirror the math; don't judge.

HARD RULES:
- 8-18 words per line.
- Cite the REAL number from the snapshot (visit count, ₱ spend, ratio).
- Voice: dry, observant, factual. No moralizing on fast food, drinks, smokes — cite a number only.
- FORBIDDEN: "should", "consider", "try", "save more", "spend less", "budget", "cut down", "you might want to", motivational fluff.
- Acceptable shapes:
  - "Fourth Jollibee this month. Usually one."
  - "SM Mayapa visits doubled — 6 in November, typical 3."
  - "Mercury Drug quiet for 67 days. Run out of something?"
- If no shift is meaningful, EXCLUDE the vendor from the response (don't pad).

Return JSON: { "lines": [{ "vendorId": "<uuid>", "line": "<sentence>" }, ...] }`;

export async function vendorHeartbeatRead(
  vendors: Vendor[],
  links: SpendVendorLink[],
  spends: Spend[],
  now: Date = new Date(),
): Promise<VendorHeartbeatRead> {
  const heartbeats = vendors.map((v) => vendorHeartbeat(v, links, spends, now));
  const worthSurfacing = heartbeats.filter((h) => h.shift !== "typical");

  // Deterministic fallback lines.
  const fallbackLines = worthSurfacing.map((h) => ({
    vendorId: h.vendor.id,
    line: fallbackHeartbeatLine(h),
  }));

  if (!hasGemini() || worthSurfacing.length === 0) {
    return { heartbeats, lines: fallbackLines };
  }

  try {
    const snapshot = worthSurfacing
      .slice(0, 6)
      .map((h) => `- vendorId=${h.vendor.id} name="${h.vendor.canonical_name}" recent_visits=${h.recentVisits} baseline_visits=${h.baselineVisits.toFixed(1)} recent_spend_php=${h.recentSpendBase.toFixed(0)} baseline_spend_php=${h.baselineSpendBase.toFixed(0)} shift=${h.shift}`)
      .join("\n");
    const res = await gemini().models.generateContent({
      model: HEAVY_MODEL,
      contents: `Vendors with cadence shifts in the last 30 days:\n\n${snapshot}\n\nReturn JSON now.`,
      config: {
        systemInstruction: SYSTEM_PROMPT,
        temperature: 0.4,
        responseMimeType: "application/json",
        responseSchema: RESPONSE_SCHEMA,
      },
    });
    const parsed = JSON.parse((res.text ?? "{}").trim()) as { lines?: Array<{ vendorId?: string; line?: string }> };
    const lines = (parsed.lines ?? [])
      .filter((l) => l && l.vendorId && l.line)
      .map((l) => ({ vendorId: l.vendorId!, line: l.line!.trim() }));
    // Fall back to deterministic for any missed vendor.
    const aiVendorIds = new Set(lines.map((l) => l.vendorId));
    for (const fb of fallbackLines) {
      if (!aiVendorIds.has(fb.vendorId)) lines.push(fb);
    }
    return { heartbeats, lines };
  } catch {
    return { heartbeats, lines: fallbackLines };
  }
}

function fallbackHeartbeatLine(h: VendorHeartbeat): string {
  const name = h.vendor.canonical_name;
  if (h.shift === "spike") {
    return `${h.recentVisits === 1 ? "First visit" : `${h.recentVisits} visits`} to ${name} this stretch — no baseline before.`;
  }
  if (h.shift === "above") {
    return `${name} up — ${h.recentVisits} visit${h.recentVisits === 1 ? "" : "s"} in 30 days vs ${h.baselineVisits.toFixed(1)} typical.`;
  }
  if (h.shift === "below") {
    return `${name} quiet — ${h.recentVisits} visit${h.recentVisits === 1 ? "" : "s"} in 30 days vs ${h.baselineVisits.toFixed(1)} typical.`;
  }
  return `${name}: ${h.recentVisits} visits, ₱${h.recentSpendBase.toFixed(0)} this stretch.`;
}
