import { getVendorsData, getVendorIconCache } from "@/lib/data/queries";
import { vendorHeartbeat } from "@/lib/ai/vendor-heartbeat";
import { vendorAbsences } from "@/lib/ai/vendor-absence";
import { BASE_CURRENCY_FALLBACK } from "@/lib/constants";
import type { CurrencyCode } from "@/lib/supabase/types";
import { VendorsView } from "./_components/vendors-view";

export const metadata = { title: "Vendors" };

export default async function VendorsPage() {
  const { vendors, aliases, links, spends, settings } = await getVendorsData();
  const vendorIconCache = await getVendorIconCache().catch(() => []);
  const baseCurrency = (settings?.base_currency ?? BASE_CURRENCY_FALLBACK) as CurrencyCode;
  const now = new Date();

  // Pure-math heartbeat per vendor (no AI call from the server page — the
  // per-vendor AI line is generated by the detail page when the user lands).
  const heartbeats = vendors
    .filter((v) => !v.archived)
    .map((v) => vendorHeartbeat(v, links, spends, now));

  // Absence detection across the full vendor pool.
  const absences = vendorAbsences(vendors, links, spends, now);

  return (
    <VendorsView
      vendors={vendors}
      aliases={aliases}
      heartbeats={heartbeats}
      absences={absences}
      links={links}
      spends={spends}
      baseCurrency={baseCurrency}
      vendorIconCache={vendorIconCache}
    />
  );
}
