-- Freelane: Calm Weather Mode — the persistent state row that powers every
-- other AI surface.
--
-- "The soul of the OS" (Hatim 2026-06-01). One honest line that describes
-- the financial weather right now, in his voice. Read by safe-to-spend, the
-- Today hero, the dashboard banner, /spending header — anywhere the user
-- needs to know "where am I today?" reads from this row.
--
-- band values (the discrete weather labels):
--   still       — runway > 60d, no overdue, no pressure; the AI mostly
--                 invites instead of nudging
--   breeze      — runway 30-60d, healthy but watchful; one small thing
--                 worth knowing
--   gust        — runway 15-30d, OR overdue cluster, OR planned big spend
--                 in window; the line gets specific about what's moving
--   storm       — runway < 15d OR negative-wallet alarm OR Tight Mode; the
--                 line says it plainly and points at one action
--   calm_after  — just came out of a storm in the last 14d; quietly
--                 celebratory but still careful
--
-- The state is GENERATED by the Calm Weather brain (src/lib/ai/calm-weather.ts)
-- on a refresh cycle (curiosity sweep, mutation hooks). It's CACHED here so
-- every read surface gets the same line — no flicker, no drift between
-- screens. Cache invalidation: any spend / payment / withdrawal / planned
-- spend mutation marks expires_at = now() so the next read regenerates.
--
-- input_snapshot stores the exact numerical inputs the brain saw so future
-- analysis (or the user reading their own history) can reconstruct WHY the
-- line was what it was at that moment.
--
-- recommendations is the structured action list the surface uses to render
-- chips ("Lock ₱5,000 for Eid?" → /plans?committed=Eid&amount=5000).

create type finance.calm_weather_band as enum (
  'still', 'breeze', 'gust', 'storm', 'calm_after'
);

create table if not exists finance.calm_weather_state (
  user_id           uuid primary key references auth.users(id) on delete cascade,
  band              finance.calm_weather_band not null default 'still',
  -- The one honest line. Freelancer voice, no goal/budget language.
  -- 80-160 chars typical.
  narrative         text not null default '',
  -- Optional second line — used only when band is gust/storm/calm_after to
  -- name the specific moving thing ("Apple Dev hits Aug 15" / "Rent + Wifi
  -- both due this week"). Nullable for still/breeze.
  secondary         text,
  -- Structured action chips. Array of:
  --   { label, kind, cta_route?, cta_params? }
  -- kind: 'lock' | 'review' | 'log' | 'breathe' | 'pre_mortem' | 'tight_open'
  recommendations   jsonb not null default '[]'::jsonb,
  -- 0-1 — how confident the brain is in this read. Drives whether the UI
  -- shows it as a calm assertion or hedges ("looks like…").
  confidence        numeric(3, 2) not null default 0.5 check (confidence between 0 and 1),
  -- The exact inputs that produced this read, for future audit + the
  -- user-facing "why does it say that?" affordance.
  -- Shape (loose): { runwayDays, dailyBurn, safeToSpend, overdueBaseTotal,
  --                  bigPlansBase, plannedBase30d, stabilityMultiplier,
  --                  observationDays, isLearning, calmAfterStormStartedAt? }
  input_snapshot    jsonb not null default '{}'::jsonb,
  -- Versioned so future model upgrades can flush old reads without losing
  -- the row.
  model_version     text not null default '1',
  generated_at      timestamptz not null default now(),
  -- When this read goes stale. Default 30 minutes from generation; mutation
  -- hooks bump to now() to force a regen on next read.
  expires_at        timestamptz not null default (now() + interval '30 minutes')
);

alter table finance.calm_weather_state enable row level security;

create policy "owner_all" on finance.calm_weather_state
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
