-- Freelane: plan_strategies — AI-proposed savings strategies attached
-- to a planned spend. Generated by plan-strategy-proposals brain (Pro,
-- 24h cache + state_hash invalidation), surfaced as ranked cards in the
-- plan detail sheet. One activated strategy per plan at a time.
--
-- When a strategy is active, safe-to-spend math subtracts the daily
-- equivalent (monthly_save_estimate / 30) from liveRemaining — Plans is
-- the first external consumer of the safe-to-spend hook in
-- src/lib/safe-to-spend.ts applyStrategy().
--
-- Strategy kinds (drive UI affordances + the AI prompt):
--   reduce_safe              — lower daily safe-to-spend for N days
--   skip_category            — skip eating-out / specific category for N weeks
--   channel_sadaka_overflow  — divert sadaka pool overflow toward the plan
--   wait_for_payment         — anchor on an upcoming client payment landing
--   cut_eating_out           — concrete cut-eating-out variant (most common)
--   pause_other_plan         — defer a different plan to free runway
--   alternative_route        — buy a cheaper alternative / used / refurb
--
-- body jsonb holds:
--   side_effects: string[] — "less eating out", "tighter weekends", …
--   monthly_save_estimate: number — denormalized for indexed reads
--   realism_score: 0..1
--   any future strategy-kind-specific payload

create table if not exists finance.plan_strategies (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references auth.users(id) on delete cascade,
  plan_id               uuid not null references finance.planned_spends(id) on delete cascade,
  strategy_kind         text not null check (
    strategy_kind in (
      'reduce_safe',
      'skip_category',
      'channel_sadaka_overflow',
      'wait_for_payment',
      'cut_eating_out',
      'pause_other_plan',
      'alternative_route'
    )
  ),
  rank                  smallint not null check (rank between 1 and 3),
  title                 text not null,
  body                  jsonb not null default '{}'::jsonb,
  estimated_completion  date,
  monthly_save_estimate numeric(14, 2),
  realism_score         numeric(4, 3),
  applicable_now        boolean not null default true,
  active                boolean not null default false,
  proposed_at           timestamptz not null default now(),
  activated_at          timestamptz,
  deactivated_at        timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- Only one active strategy per plan. activateStrategy() is responsible
-- for deactivating any existing active row in the same transaction.
create unique index if not exists plan_strategies_one_active_per_plan
  on finance.plan_strategies (plan_id)
  where active = true;

-- Per-user + per-plan reader index — the page loader fetches active
-- strategies for the user, the detail sheet fetches all rank-1..3 for
-- one plan.
create index if not exists plan_strategies_user_plan_idx
  on finance.plan_strategies (user_id, plan_id);

-- Used for cross-page aggregation: "what strategies are currently
-- active across all my plans" — drives the safe-to-spend daily
-- reduction sum.
create index if not exists plan_strategies_user_active_idx
  on finance.plan_strategies (user_id)
  where active = true;

create trigger plan_strategies_touch
  before update on finance.plan_strategies
  for each row execute function finance.touch_updated_at();

alter table finance.plan_strategies enable row level security;

create policy "owner_all" on finance.plan_strategies
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
